version: "3.8"

services:
  app:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - .:/app       # monta o código local dentro do container
      - /app/node_modules  # evita conflito entre node_modules local e do container
    environment:
      - NODE_ENV=development
    command: npm run dev
    env_file:
      - .env

